### ISSUE TITLE
change recommended test app in readme.md

### ISSUE THREAD

**Issue by offalynne** [ThaumicTom/webpad#1]
gamepad-tester.com has been loaded with sketchy adware and autoplay ads and is apparently advertising sale of scraped user data

suggest pointing users to https://greggman.github.io/html5-gamepad-test/ or https://apps.nektro.net/gamepad

**Comment by thaumictom** [comment]
Thanks for pointing it out and giving suggestions for alternatives. I changed it accordingly. The website is indeed filled with many ads when not using a proper ad blocker.
